# Generated by Django 5.0.1 on 2024-01-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
